[cl-json-pointer]
src.git = "https://github.com/y2q-actionman/cl-json-pointer"
fetch.git = "https://github.com/y2q-actionman/cl-json-pointer"

[termp]
src.git = "https://github.com/vindarel/termp"
fetch.git = "https://github.com/vindarel/termp"
