# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cl-json-pointer = {
    pname = "cl-json-pointer";
    version = "f6760e2a02972783f96b92a15f801e14a6828e0c";
    src = fetchgit {
      url = "https://github.com/y2q-actionman/cl-json-pointer";
      rev = "f6760e2a02972783f96b92a15f801e14a6828e0c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-UKzPSpF1WXUC0D2Qq7UlMIh1DhKjnX1D0/AJxks56iw=";
    };
    date = "2022-09-14";
  };
  termp = {
    pname = "termp";
    version = "29789fe83db624679b6f341e3fae3f2577ce6a45";
    src = fetchgit {
      url = "https://github.com/vindarel/termp";
      rev = "29789fe83db624679b6f341e3fae3f2577ce6a45";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-kDYbM0fYJIUbuBMOnHVMfhTtu7CTid2EAs8THMBmJQ8=";
    };
    date = "2024-09-02";
  };
}
